// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: index_runs.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIndexRun = `-- name: CreateIndexRun :one
INSERT INTO index_runs (project_id, source_id, status)
VALUES ($1, $2, 'pending')
RETURNING id, project_id, source_id, status, started_at, completed_at, files_processed, symbols_found, edges_found, error_message, metadata, created_at
`

type CreateIndexRunParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	SourceID  pgtype.UUID `json:"source_id"`
}

func (q *Queries) CreateIndexRun(ctx context.Context, arg CreateIndexRunParams) (IndexRun, error) {
	row := q.db.QueryRow(ctx, createIndexRun, arg.ProjectID, arg.SourceID)
	var i IndexRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FilesProcessed,
		&i.SymbolsFound,
		&i.EdgesFound,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getIndexRun = `-- name: GetIndexRun :one
SELECT id, project_id, source_id, status, started_at, completed_at, files_processed, symbols_found, edges_found, error_message, metadata, created_at FROM index_runs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIndexRun(ctx context.Context, id uuid.UUID) (IndexRun, error) {
	row := q.db.QueryRow(ctx, getIndexRun, id)
	var i IndexRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FilesProcessed,
		&i.SymbolsFound,
		&i.EdgesFound,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listIndexRunsByProject = `-- name: ListIndexRunsByProject :many
SELECT ir.id, ir.project_id, ir.source_id, ir.status, ir.started_at, ir.completed_at, ir.files_processed, ir.symbols_found, ir.edges_found, ir.error_message, ir.metadata, ir.created_at FROM index_runs ir
JOIN projects p ON ir.project_id = p.id
WHERE p.slug = $1
ORDER BY ir.created_at DESC
LIMIT $2 OFFSET $3
`

type ListIndexRunsByProjectParams struct {
	Slug   string `json:"slug"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListIndexRunsByProject(ctx context.Context, arg ListIndexRunsByProjectParams) ([]IndexRun, error) {
	rows, err := q.db.Query(ctx, listIndexRunsByProject, arg.Slug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IndexRun{}
	for rows.Next() {
		var i IndexRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilesProcessed,
			&i.SymbolsFound,
			&i.EdgesFound,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndexRunsByProjectID = `-- name: ListIndexRunsByProjectID :many
SELECT id, project_id, source_id, status, started_at, completed_at, files_processed, symbols_found, edges_found, error_message, metadata, created_at FROM index_runs WHERE project_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListIndexRunsByProjectIDParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListIndexRunsByProjectID(ctx context.Context, arg ListIndexRunsByProjectIDParams) ([]IndexRun, error) {
	rows, err := q.db.Query(ctx, listIndexRunsByProjectID, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IndexRun{}
	for rows.Next() {
		var i IndexRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilesProcessed,
			&i.SymbolsFound,
			&i.EdgesFound,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIndexRunStats = `-- name: UpdateIndexRunStats :exec
UPDATE index_runs
SET files_processed = $2, symbols_found = $3, edges_found = $4
WHERE id = $1
`

type UpdateIndexRunStatsParams struct {
	ID             uuid.UUID `json:"id"`
	FilesProcessed int32     `json:"files_processed"`
	SymbolsFound   int32     `json:"symbols_found"`
	EdgesFound     int32     `json:"edges_found"`
}

func (q *Queries) UpdateIndexRunStats(ctx context.Context, arg UpdateIndexRunStatsParams) error {
	_, err := q.db.Exec(ctx, updateIndexRunStats,
		arg.ID,
		arg.FilesProcessed,
		arg.SymbolsFound,
		arg.EdgesFound,
	)
	return err
}

const updateIndexRunStatus = `-- name: UpdateIndexRunStatus :exec
UPDATE index_runs
SET status = $2,
    started_at = CASE WHEN $2 = 'running' THEN now() ELSE started_at END,
    completed_at = CASE WHEN $2 IN ('completed', 'failed', 'cancelled') THEN now() ELSE completed_at END,
    error_message = $3
WHERE id = $1
`

type UpdateIndexRunStatusParams struct {
	ID           uuid.UUID `json:"id"`
	Status       string    `json:"status"`
	ErrorMessage *string   `json:"error_message"`
}

func (q *Queries) UpdateIndexRunStatus(ctx context.Context, arg UpdateIndexRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateIndexRunStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
