// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (project_id, name, source_type, connection_uri, config)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, source_type, connection_uri, config, last_synced_at, created_at, updated_at, last_commit_sha
`

type CreateSourceParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	Name          string    `json:"name"`
	SourceType    string    `json:"source_type"`
	ConnectionUri *string   `json:"connection_uri"`
	Config        []byte    `json:"config"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.ProjectID,
		arg.Name,
		arg.SourceType,
		arg.ConnectionUri,
		arg.Config,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.SourceType,
		&i.ConnectionUri,
		&i.Config,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCommitSha,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = $1
`

func (q *Queries) DeleteSource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSource, id)
	return err
}

const getSource = `-- name: GetSource :one
SELECT id, project_id, name, source_type, connection_uri, config, last_synced_at, created_at, updated_at, last_commit_sha FROM sources WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSource(ctx context.Context, id uuid.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.SourceType,
		&i.ConnectionUri,
		&i.Config,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCommitSha,
	)
	return i, err
}

const listSourcesByProject = `-- name: ListSourcesByProject :many
SELECT s.id, s.project_id, s.name, s.source_type, s.connection_uri, s.config, s.last_synced_at, s.created_at, s.updated_at, s.last_commit_sha FROM sources s
JOIN projects p ON s.project_id = p.id
WHERE p.slug = $1
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSourcesByProjectParams struct {
	Slug   string `json:"slug"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListSourcesByProject(ctx context.Context, arg ListSourcesByProjectParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByProject, arg.Slug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.SourceType,
			&i.ConnectionUri,
			&i.Config,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastCommitSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesByProjectID = `-- name: ListSourcesByProjectID :many
SELECT id, project_id, name, source_type, connection_uri, config, last_synced_at, created_at, updated_at, last_commit_sha FROM sources WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSourcesByProjectID(ctx context.Context, projectID uuid.UUID) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.SourceType,
			&i.ConnectionUri,
			&i.Config,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastCommitSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSourceLastCommitSHA = `-- name: UpdateSourceLastCommitSHA :exec
UPDATE sources SET last_commit_sha = $2, updated_at = now() WHERE id = $1
`

type UpdateSourceLastCommitSHAParams struct {
	ID            uuid.UUID `json:"id"`
	LastCommitSha *string   `json:"last_commit_sha"`
}

func (q *Queries) UpdateSourceLastCommitSHA(ctx context.Context, arg UpdateSourceLastCommitSHAParams) error {
	_, err := q.db.Exec(ctx, updateSourceLastCommitSHA, arg.ID, arg.LastCommitSha)
	return err
}

const updateSourceLastSynced = `-- name: UpdateSourceLastSynced :exec
UPDATE sources SET last_synced_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateSourceLastSynced(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSourceLastSynced, id)
	return err
}
