// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const checkTenantAccess = `-- name: CheckTenantAccess :one
SELECT EXISTS(
    SELECT 1 FROM memberships WHERE tenant_id = $1 AND user_sub = $2
) AS has_access
`

type CheckTenantAccessParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserSub  string    `json:"user_sub"`
}

func (q *Queries) CheckTenantAccess(ctx context.Context, arg CheckTenantAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkTenantAccess, arg.TenantID, arg.UserSub)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (tenant_id, user_sub, role)
VALUES ($1, $2, $3)
RETURNING tenant_id, user_sub, role, created_at
`

type CreateMembershipParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserSub  string    `json:"user_sub"`
	Role     string    `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.TenantID, arg.UserSub, arg.Role)
	var i Membership
	err := row.Scan(
		&i.TenantID,
		&i.UserSub,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug, settings)
VALUES ($1, $2, $3)
RETURNING id, name, slug, settings, created_at, updated_at
`

type CreateTenantParams struct {
	Name     string `json:"name"`
	Slug     string `json:"slug"`
	Settings []byte `json:"settings"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Slug, arg.Settings)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE tenant_id = $1 AND user_sub = $2
`

type DeleteMembershipParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserSub  string    `json:"user_sub"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.TenantID, arg.UserSub)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT tenant_id, user_sub, role, created_at FROM memberships WHERE tenant_id = $1 AND user_sub = $2 LIMIT 1
`

type GetMembershipParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserSub  string    `json:"user_sub"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.TenantID, arg.UserSub)
	var i Membership
	err := row.Scan(
		&i.TenantID,
		&i.UserSub,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, slug, settings, created_at, updated_at FROM tenants WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenant(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, settings, created_at, updated_at FROM tenants WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipsByTenant = `-- name: ListMembershipsByTenant :many
SELECT tenant_id, user_sub, role, created_at FROM memberships WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListMembershipsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.TenantID,
			&i.UserSub,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, settings, created_at, updated_at FROM tenants ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
