// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/maraichr/lattice/pkg/models"
)

type ColumnLineageEdge struct {
	SourceID       string  `json:"sourceId"`
	TargetID       string  `json:"targetId"`
	DerivationType string  `json:"derivationType"`
	Expression     *string `json:"expression,omitempty"`
}

type ColumnLineageGraph struct {
	Nodes        []*ColumnLineageNode `json:"nodes"`
	Edges        []*ColumnLineageEdge `json:"edges"`
	RootColumnID string               `json:"rootColumnId"`
}

type ColumnLineageNode struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	QualifiedName string `json:"qualifiedName"`
	TableName     string `json:"tableName"`
	Kind          string `json:"kind"`
}

type CreateProjectInput struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description,omitempty"`
}

type CreateSourceInput struct {
	Name          string     `json:"name"`
	SourceType    SourceType `json:"sourceType"`
	ConnectionURI *string    `json:"connectionUri,omitempty"`
	Config        *string    `json:"config,omitempty"`
}

type ImpactAnalysisResult struct {
	Root             *ImpactSymbol `json:"root"`
	ChangeType       ChangeType    `json:"changeType"`
	DirectImpact     []*ImpactNode `json:"directImpact"`
	TransitiveImpact []*ImpactNode `json:"transitiveImpact"`
	TotalAffected    int           `json:"totalAffected"`
}

type ImpactNode struct {
	Symbol   *ImpactSymbol `json:"symbol"`
	Depth    int           `json:"depth"`
	Severity Severity      `json:"severity"`
	EdgeType string        `json:"edgeType"`
	Path     []string      `json:"path"`
}

type ImpactSymbol struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	QualifiedName string `json:"qualifiedName"`
	Kind          string `json:"kind"`
	Language      string `json:"language"`
}

type IndexRun struct {
	ID             string         `json:"id"`
	Status         IndexRunStatus `json:"status"`
	FilesProcessed int            `json:"filesProcessed"`
	SymbolsFound   int            `json:"symbolsFound"`
	EdgesFound     int            `json:"edgesFound"`
	StartedAt      *time.Time     `json:"startedAt,omitempty"`
	CompletedAt    *time.Time     `json:"completedAt,omitempty"`
	ErrorMessage   *string        `json:"errorMessage,omitempty"`
	CreatedAt      time.Time      `json:"createdAt"`
}

type LineageGraph struct {
	Nodes        []*models.Symbol     `json:"nodes"`
	Edges        []*models.SymbolEdge `json:"edges"`
	RootSymbolID string               `json:"rootSymbolId"`
}

type Mutation struct {
}

type Project struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description *string     `json:"description,omitempty"`
	Sources     []*Source   `json:"sources"`
	IndexRuns   []*IndexRun `json:"indexRuns"`
	SymbolCount int         `json:"symbolCount"`
	EdgeCount   int         `json:"edgeCount"`
	CreatedAt   time.Time   `json:"createdAt"`
	UpdatedAt   time.Time   `json:"updatedAt"`
}

type ProjectConnection struct {
	Nodes      []*Project `json:"nodes"`
	TotalCount int        `json:"totalCount"`
}

type Query struct {
}

type SemanticSearchResult struct {
	Symbol *models.Symbol `json:"symbol"`
	Score  float64        `json:"score"`
}

type Source struct {
	ID           string     `json:"id"`
	Name         string     `json:"name"`
	SourceType   SourceType `json:"sourceType"`
	LastSyncedAt *time.Time `json:"lastSyncedAt,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
}

type UpdateProjectInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type ChangeType string

const (
	ChangeTypeModify ChangeType = "MODIFY"
	ChangeTypeDelete ChangeType = "DELETE"
	ChangeTypeRename ChangeType = "RENAME"
)

var AllChangeType = []ChangeType{
	ChangeTypeModify,
	ChangeTypeDelete,
	ChangeTypeRename,
}

func (e ChangeType) IsValid() bool {
	switch e {
	case ChangeTypeModify, ChangeTypeDelete, ChangeTypeRename:
		return true
	}
	return false
}

func (e ChangeType) String() string {
	return string(e)
}

func (e *ChangeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChangeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChangeType", str)
	}
	return nil
}

func (e ChangeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChangeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChangeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DerivationType string

const (
	DerivationTypeDirectCopy  DerivationType = "DIRECT_COPY"
	DerivationTypeTransform   DerivationType = "TRANSFORM"
	DerivationTypeAggregate   DerivationType = "AGGREGATE"
	DerivationTypeFilter      DerivationType = "FILTER"
	DerivationTypeJoin        DerivationType = "JOIN"
	DerivationTypeConditional DerivationType = "CONDITIONAL"
)

var AllDerivationType = []DerivationType{
	DerivationTypeDirectCopy,
	DerivationTypeTransform,
	DerivationTypeAggregate,
	DerivationTypeFilter,
	DerivationTypeJoin,
	DerivationTypeConditional,
}

func (e DerivationType) IsValid() bool {
	switch e {
	case DerivationTypeDirectCopy, DerivationTypeTransform, DerivationTypeAggregate, DerivationTypeFilter, DerivationTypeJoin, DerivationTypeConditional:
		return true
	}
	return false
}

func (e DerivationType) String() string {
	return string(e)
}

func (e *DerivationType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DerivationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DerivationType", str)
	}
	return nil
}

func (e DerivationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DerivationType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DerivationType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type IndexRunStatus string

const (
	IndexRunStatusPending   IndexRunStatus = "PENDING"
	IndexRunStatusRunning   IndexRunStatus = "RUNNING"
	IndexRunStatusCompleted IndexRunStatus = "COMPLETED"
	IndexRunStatusFailed    IndexRunStatus = "FAILED"
	IndexRunStatusCancelled IndexRunStatus = "CANCELLED"
)

var AllIndexRunStatus = []IndexRunStatus{
	IndexRunStatusPending,
	IndexRunStatusRunning,
	IndexRunStatusCompleted,
	IndexRunStatusFailed,
	IndexRunStatusCancelled,
}

func (e IndexRunStatus) IsValid() bool {
	switch e {
	case IndexRunStatusPending, IndexRunStatusRunning, IndexRunStatusCompleted, IndexRunStatusFailed, IndexRunStatusCancelled:
		return true
	}
	return false
}

func (e IndexRunStatus) String() string {
	return string(e)
}

func (e *IndexRunStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IndexRunStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IndexRunStatus", str)
	}
	return nil
}

func (e IndexRunStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *IndexRunStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e IndexRunStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LineageDirection string

const (
	LineageDirectionUpstream   LineageDirection = "UPSTREAM"
	LineageDirectionDownstream LineageDirection = "DOWNSTREAM"
	LineageDirectionBoth       LineageDirection = "BOTH"
)

var AllLineageDirection = []LineageDirection{
	LineageDirectionUpstream,
	LineageDirectionDownstream,
	LineageDirectionBoth,
}

func (e LineageDirection) IsValid() bool {
	switch e {
	case LineageDirectionUpstream, LineageDirectionDownstream, LineageDirectionBoth:
		return true
	}
	return false
}

func (e LineageDirection) String() string {
	return string(e)
}

func (e *LineageDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LineageDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LineageDirection", str)
	}
	return nil
}

func (e LineageDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LineageDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LineageDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Severity string

const (
	SeverityCritical Severity = "CRITICAL"
	SeverityHigh     Severity = "HIGH"
	SeverityMedium   Severity = "MEDIUM"
	SeverityLow      Severity = "LOW"
)

var AllSeverity = []Severity{
	SeverityCritical,
	SeverityHigh,
	SeverityMedium,
	SeverityLow,
}

func (e Severity) IsValid() bool {
	switch e {
	case SeverityCritical, SeverityHigh, SeverityMedium, SeverityLow:
		return true
	}
	return false
}

func (e Severity) String() string {
	return string(e)
}

func (e *Severity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Severity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Severity", str)
	}
	return nil
}

func (e Severity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Severity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Severity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SourceType string

const (
	SourceTypeGit        SourceType = "GIT"
	SourceTypeDatabase   SourceType = "DATABASE"
	SourceTypeFilesystem SourceType = "FILESYSTEM"
	SourceTypeUpload     SourceType = "UPLOAD"
	SourceTypeS3         SourceType = "S3"
)

var AllSourceType = []SourceType{
	SourceTypeGit,
	SourceTypeDatabase,
	SourceTypeFilesystem,
	SourceTypeUpload,
	SourceTypeS3,
}

func (e SourceType) IsValid() bool {
	switch e {
	case SourceTypeGit, SourceTypeDatabase, SourceTypeFilesystem, SourceTypeUpload, SourceTypeS3:
		return true
	}
	return false
}

func (e SourceType) String() string {
	return string(e)
}

func (e *SourceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SourceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SourceType", str)
	}
	return nil
}

func (e SourceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SourceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SourceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
